/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import controller.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author neubr
 */
public class Menu_Dashboard extends javax.swing.JPanel {

    private Connection conn;
    /**
     * Creates new form Menu_Dashboard
     */
    public Menu_Dashboard() {
        initComponents();
        conn = controller.koneksi.getKoneksi();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        card_kategori = new Custom.Custom_JPanelRounded();
        lb_kategori = new javax.swing.JLabel();
        lb_jumlahkategori = new javax.swing.JLabel();
        card_produk = new Custom.Custom_JPanelRounded();
        lb_produk = new javax.swing.JLabel();
        lb_jumlahproduk = new javax.swing.JLabel();
        card_penjualan = new Custom.Custom_JPanelRounded();
        lb_penjualan = new javax.swing.JLabel();
        lb_jumlahpenjualan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1026, 658));

        card_kategori.setBackground(new java.awt.Color(255, 0, 0));
        card_kategori.setPreferredSize(new java.awt.Dimension(207, 121));
        card_kategori.setRoundBottomLeft(30);
        card_kategori.setRoundBottomRight(30);
        card_kategori.setRoundTopLeft(30);
        card_kategori.setRoundTopRight(30);

        lb_kategori.setBackground(new java.awt.Color(255, 255, 255));
        lb_kategori.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_kategori.setForeground(new java.awt.Color(255, 255, 255));
        lb_kategori.setText("KATEGORI");

        lb_jumlahkategori.setBackground(new java.awt.Color(102, 102, 102));
        lb_jumlahkategori.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahkategori.setForeground(new java.awt.Color(255, 255, 255));
        lb_jumlahkategori.setText("20");

        javax.swing.GroupLayout card_kategoriLayout = new javax.swing.GroupLayout(card_kategori);
        card_kategori.setLayout(card_kategoriLayout);
        card_kategoriLayout.setHorizontalGroup(
            card_kategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_kategoriLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(card_kategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_jumlahkategori)
                    .addComponent(lb_kategori))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        card_kategoriLayout.setVerticalGroup(
            card_kategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_kategoriLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lb_kategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_jumlahkategori)
                .addContainerGap())
        );

        card_produk.setBackground(new java.awt.Color(255, 0, 0));
        card_produk.setRoundBottomLeft(30);
        card_produk.setRoundBottomRight(30);
        card_produk.setRoundTopLeft(30);
        card_produk.setRoundTopRight(30);

        lb_produk.setBackground(new java.awt.Color(255, 255, 255));
        lb_produk.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_produk.setForeground(new java.awt.Color(255, 255, 255));
        lb_produk.setText("PRODUK");

        lb_jumlahproduk.setBackground(new java.awt.Color(102, 102, 102));
        lb_jumlahproduk.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahproduk.setForeground(new java.awt.Color(255, 255, 255));
        lb_jumlahproduk.setText("4");

        javax.swing.GroupLayout card_produkLayout = new javax.swing.GroupLayout(card_produk);
        card_produk.setLayout(card_produkLayout);
        card_produkLayout.setHorizontalGroup(
            card_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_produkLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(card_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card_produkLayout.createSequentialGroup()
                        .addComponent(lb_jumlahproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(card_produkLayout.createSequentialGroup()
                        .addComponent(lb_produk)
                        .addGap(20, 74, Short.MAX_VALUE))))
        );
        card_produkLayout.setVerticalGroup(
            card_produkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_produkLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_produk)
                .addGap(18, 18, 18)
                .addComponent(lb_jumlahproduk)
                .addContainerGap())
        );

        card_penjualan.setBackground(new java.awt.Color(255, 0, 0));
        card_penjualan.setRoundBottomLeft(30);
        card_penjualan.setRoundBottomRight(30);
        card_penjualan.setRoundTopLeft(30);
        card_penjualan.setRoundTopRight(30);

        lb_penjualan.setBackground(new java.awt.Color(255, 255, 255));
        lb_penjualan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lb_penjualan.setForeground(new java.awt.Color(255, 255, 255));
        lb_penjualan.setText("PENJUALAN");

        lb_jumlahpenjualan.setBackground(new java.awt.Color(102, 102, 102));
        lb_jumlahpenjualan.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lb_jumlahpenjualan.setForeground(new java.awt.Color(255, 255, 255));
        lb_jumlahpenjualan.setText("12");

        javax.swing.GroupLayout card_penjualanLayout = new javax.swing.GroupLayout(card_penjualan);
        card_penjualan.setLayout(card_penjualanLayout);
        card_penjualanLayout.setHorizontalGroup(
            card_penjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_penjualanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_jumlahpenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_penjualanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_penjualan)
                .addGap(38, 38, 38))
        );
        card_penjualanLayout.setVerticalGroup(
            card_penjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_penjualanLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_penjualan)
                .addGap(18, 18, 18)
                .addComponent(lb_jumlahpenjualan)
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Master Data > Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(card_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(card_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(card_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(card_produk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(card_kategori, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(card_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(461, 461, 461))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.Custom_JPanelRounded card_kategori;
    private Custom.Custom_JPanelRounded card_penjualan;
    private Custom.Custom_JPanelRounded card_produk;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_jumlahkategori;
    private javax.swing.JLabel lb_jumlahpenjualan;
    private javax.swing.JLabel lb_jumlahproduk;
    private javax.swing.JLabel lb_kategori;
    private javax.swing.JLabel lb_penjualan;
    private javax.swing.JLabel lb_produk;
    // End of variables declaration//GEN-END:variables

    
    private int jumlahKategori(){
        int totalKategori = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM kategori_produk";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            if(rs.next()){
                totalKategori = rs.getInt("total");
            }
        } catch (Exception e){
            e.printStackTrace();
        }
        return totalKategori;
    }
    
    
     private int jumlahProduk(){
        int totalproduk = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM produk";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            if(rs.next()){
                totalproduk = rs.getInt("total");
            }
        } catch (Exception e){
            e.printStackTrace();
        }
        return totalproduk;
    }
     
      private int jumlahPenjualan(){
        int totalPenjualan = 0;
        
        try {
            String sql = "SELECT COUNT(*) AS total FROM penjualan";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            if(rs.next()){
                totalPenjualan = rs.getInt("total");
            }
        } catch (Exception e){
            e.printStackTrace();
        }
        return totalPenjualan;
    }
     
    private void loadData() {
       lb_jumlahkategori.setText(String.valueOf(jumlahKategori()));
       lb_jumlahproduk.setText(String.valueOf(jumlahProduk()));
       lb_jumlahpenjualan.setText(String.valueOf(jumlahPenjualan()));
    }
}

